In [1]:
import numpy as np

In [2]:
L = [1, 2, 3]

In [3]:
A = np.array([1, 2, 3])

In [5]:
for e in L:
  print(e)

1
2
3


In [7]:
L.append(4)

In [8]:
L+[5]

[1, 2, 3, 4, 5]

In [9]:
A + np.array([4])

array([5, 6, 7])

In [10]:
A + np.array([4,5,6])

array([5, 7, 9])

In [11]:
2+4

6

In [12]:
2 +A

array([3, 4, 5])

In [13]:
2*A

array([2, 4, 6])

In [14]:
2*L

[1, 2, 3, 4, 1, 2, 3, 4]

In [15]:
L+L

[1, 2, 3, 4, 1, 2, 3, 4]

In [17]:
L2 = []

In [19]:
for e in L:
  L2.append(e+3)

In [20]:
L2

[4, 5, 6, 7]

In [21]:
L

[1, 2, 3, 4]

In [24]:
L3 = [i+3 for i in L]

In [25]:
L3

[4, 5, 6, 7]

In [26]:
L4 = [x**2 for x in L]

In [27]:
L4

[1, 4, 9, 16]

In [28]:
# [1, 4, 9, 16] 으로 출력되도록 해보세요.
L4 = []
for i in L:
  L4.append(i**2)

In [29]:
L4

[1, 4, 9, 16]

In [30]:
A**2

array([1, 4, 9])

In [31]:
A

array([1, 2, 3])

In [32]:
np.sqrt(A) # 루트 씌우기(제곱근 구하기)

array([1.        , 1.41421356, 1.73205081])

In [33]:
np.log(A) # 로그 함수

array([0.        , 0.69314718, 1.09861229])

In [34]:
np.exp(A)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [35]:
np.tanh(A)

array([0.76159416, 0.96402758, 0.99505475])

In [36]:
L = [[1, 2], [3, 4]]

In [37]:
L

[[1, 2], [3, 4]]

In [38]:
L[0]

[1, 2]

In [39]:
L[0][1]

2

In [40]:
A = np.array([[1,2], [3,4]])

In [41]:
A[0][1]

np.int64(2)

In [42]:
A[0,1]

np.int64(2)

In [43]:
A[:,0]

array([1, 3])

In [44]:
A.T #TRANSPOSE 전치하다 - 행과 열을 서로 뒤바꾸는 것

array([[1, 3],
       [2, 4]])